name: "! 435 fix"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: exp
      - run: node --check app.js
      - run: node --check bible-api.js
