name: Deploy Json-Ver to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - json-ver

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: Inject BUILD_ID
        run: |
          echo "Injecting BUILD_ID: $GITHUB_SHA"
          sed -i "s/__BUILD_ID__/$GITHUB_SHA/g" sw.js
          sed -i "s/__BUILD_ID__/$GITHUB_SHA/g" index.html

      - name: Deploy to GitHub Pages (json-ver)
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          destination_dir: json-ver
          keep_files: true
