name: Deploy Json-Ver to GitHub Pages

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - json-ver

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages (json-ver)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          destination_dir: json-ver
          keep_files: true
